# Stage 1: Build Angular frontend
FROM node:18-alpine
WORKDIR /app

# Copy package.json and package-lock.json (if it exists) and install dependencies
COPY package*.json ./
RUN npm install --include=dev
RUN npm install -g @angular/cli
# Expose port for Angular dev server
EXPOSE 4200 4200

# Start the Angular development server
CMD ["ng", "serve", "--host", "0.0.0.0"] 