FROM node:18-alpine
WORKDIR /app

# Expose port for Angular dev server
EXPOSE 4200

# CMD to install dependencies and run Angular server
CMD npm install --include=dev && npm install -g @angular/cli && ng serve --host 0.0.0.0 --poll 2000
