version: '3.8'

services:
  php:
    build:
      dockerfile: ./php/Dockerfile
      context: ./
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_PASSWORD: root
      JOOMLA_DB_NAME: joomla
    volumes:
      - ../php:/var/www/html/team-portal
      - ./php/.htaccess:/var/www/html/.htaccess
      - ./php/php-development.ini:/usr/local/etc/php/php.ini
      - type: bind
        source: ./php/www-root
        target: /var/www/html

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - '8081:80'

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 8025:8025
      - 1025:1025
